### ISSUE TITLE
D3 Density Modification.

### ISSUE THREAD

**Issue by 5teffen** [5teffen/ML-Explainer#22]
Attempt to fix density such that it appears as a smooth gradient. Might require consulting with someone with more experience.

**Comment by oscargomezq** [comment]
For now, try to debug it so that fineness can be changed (putting 100 makes it go over the edges)

**Comment by 5teffen** [comment]
Fixed the overflow.

**Comment by oscargomezq** [comment]
- Try out CSS linear gradients with values from the KDE.

**Comment by 5teffen** [comment]
I think this has been finished.
